failing test for LIBERAPAYCOM-87
```
  File "wireup.py", line 777, in <module>
    main()
  File "wireup.py", line 770, in main
    from liberapay.main import website
  File "/opt/python/ondeck/app/liberapay/main.py", line 79, in <module>
    website.__dict__.update(wireup.full_algorithm.run(**website.__dict__))
  File "site-packages/algorithm.py", line 342, in run
    loop(False)
  File "site-packages/algorithm.py", line 333, in loop
    loop(True)
  File "site-packages/algorithm.py", line 321, in loop
    new_state = function(**deps.as_kwargs)
  File "liberapay/wireup.py", line 107, in csp
    return {'csp': CSP(csp)}
  File "liberapay/wireup.py", line 84, in __new__
    self.directives = dict(d.split(b' ', 1) for d in self.split(b';') if d)
ValueError: dictionary update sequence element #6 has length 1; 2 is required
```