fix order of changes in migrations.sql
```
BEGIN
ERROR:  cannot drop table participants column is_suspicious because other objects depend on it
DETAIL:  view current_takes depends on table participants column is_suspicious
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
```